
name: Entregables 1,2,3
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: paso1 - actualizar pip
        run: python -m pip install --upgrade pip      

      - name: paso2 - instalar dependencias
        run: pip install -r requirements.txt

      - name: paso3 - Ejecutar script actividad 1
        run: python src/actividad_1.py

      - name: paso4 - Ejecutar script actividad 2
        run: python src/actividad_2.py

      - name: paso5 - Ejecutar script actividad 3
        run: python src/actividad_3.py

      - name: Commit and Push changes

        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Entregables_actividad_1,2 y 3
          commit_user_name: ubert Toro [GitHub Actions]
          commit_user_email: alonso.toro@est.iudigital.edu.co
          commit_author: ubert toro <alonso.toro@est.iudigital.edu.co>
          file_pattern: src/evidencias/actividad_3/*